export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.dotnet"
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"
export DOTNET_ROOT="$HOME/.dotnet"
export GOPATH="$HOME/.go"
export WINELOADER="$HOME/.local/bin/wineloader.sh"
