# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[input]
prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]

[manager]
prepend_keymap = [
  { on = "q", run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
  { on = "Q", run = "quit", desc = "Exit the process and write cwd-file" },
  { on = "d", run = "remove --permanently", desc = "Permanently delete the files" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "<C-p>", run = "plugin max-preview", desc = "Maximize or restore preview" },
  { on = "!", run = "shell \"nu -li\" --block --confirm", desc = "Launch shell" },
  { on = ["m", "c"], run = "linemode custom", desc = "Linemode: custom" },
  { on = ["g", "/"], run = "cd /", desc = "Go to /" },
  { on = ["g", "D"], run = "cd /data", desc = "Go to /data" },
  { on = ["g", "m", "d"], run = "cd /mnt/Dropbox", desc = "Go to /mnt/Dropbox" },
  { on = ["g", "m", "o"], run = "cd /mnt/OneDrive", desc = "Go to /mnt/OneDrive" },
  { on = ["g", "m", "p"], run = "cd /mnt/pCloud", desc = "Go to /mnt/pCloud" },
  { on = ["g", "m", "q"], run = "cd /mnt/QNAP64", desc = "Go to /mnt/QNAP64" },
  { on = "<C-t>", run = "tab_create --current", desc = "Create a new tab with CWD" },
]

[tasks]
prepend_keymap = [
  { on = "q", run = "close", desc = "Close task manager" },
]

[cmp]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]

[help]
prepend_keymap = [
  { on = "/", run = "filter", desc = "Apply a filter for the help items" },
]
