# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode = "custom"
show_hidden = true

[preview]
image_delay = 0

[tasks]
suppress_preload = true

[opener]
edit = [
  { run = '$EDITOR "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = '%EDITOR% "%*"', desc = "$EDITOR", block = true, for = "windows" },
]

[[plugin.prepend_preloaders]]
name = "/mnt/**"
run = "noop"
