- name: Invalid newline between opening braces
  pattern: '{\n\n+\s*{'
  error: true

- name: Invalid newline between closing braces
  pattern: '}\n\n+\s*}'
  error: true

- name: Abuse of newlines is strictly forbidden
  pattern: '\n\n\n\n'
  error: true
