#!/usr/bin/env bash

set -euo pipefail

[[ ! -d ~/.local/bin ]] && mkdir -p ~/.local/bin

export PATH="$HOME/.local/bin:$PATH"

has() {
  command -v "$1" 1>/dev/null 2>&1
}

# If we're on arch we can do everything with pacman.
if has pacman; then
  if ! has nu; then
    sudo pacman -Sy --noconfirm nushell
  fi
  if ! has gh; then
    sudo pacman -Sy --noconfirm github-cli
  fi
  exit
fi

# If we already have nushell, we're done.
if has nu; then
  exit 0
fi

# Install GitHub CLI, because we need it to download the latest nushell release.
if ! has gh; then
  if has dnf; then
    sudo dnf install -y gh
  fi
fi

# Must be authenticated with GitHub
if ! gh auth status 2>&1 | grep -q "Logged in to"; then
  printf "\033[0;31mNot logged into GitHub CLI, logging in\n"
  gh auth login
fi

# Install the latest nushell release from GitHub releases to ~/.local/bin.
temp_directory=$(mktemp -d)
trap 'rm -rf -- "$temp_directory"' EXIT
gh release download -R nushell/nushell -p '*x86_64-unknown-linux-gnu.tar.gz' -O - | tar xz -C "$temp_directory"
find "$temp_directory" -type f -executable -exec cp "{}" "$HOME/.local/bin" ';'
