#!/usr/bin/env bash

set -euo pipefail

has() {
  command -v "$1" 1>/dev/null 2>&1
}

# Install GitHub cli, because we need it to download the latest nushell release.
if ! has gh; then
  if has dnf; then
    sudo dnf install gh -y
  elif has pacman; then
    sudo pacman -Sy --noconfirm github-cli
  fi
fi

# Must be authenticated with GitHub
if ! gh auth status 2>&1 | grep -q "Logged in to"; then
  printf "\033[0;31mNot logged into GitHub CLI, logging in\n"
  gh auth login
fi

# Install the latest nushell release from GitHub releases to ~/.local/bin.
if ! has nu; then
  temp_directory=$(mktemp -d)
  trap 'rm -rf -- "$temp_directory"' EXIT
  gh release download -R nushell/nushell -p '*x86_64-unknown-linux-gnu.tar.gz' -O - | tar xz -C "$temp_directory"
  [[ ! -d ~/.local/bin ]] && mkdir -p ~/.local/bin
  find "$temp_directory" -type f -executable -exec cp "{}" "$HOME/.local/bin" ';'
fi
