os:
  editPreset: nvim
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  border: rounded
  theme:
    optionsTextColor:
      - "#b8bb26"
    inactiveBorderColor:
      - "#83a598"
    defaultFgColor:
      - "#ebdbb2"
    cherryPickedCommitFgColor:
      - "#b8bb26"
    cherryPickedCommitBgColor:
      - "#83a598"
    activeBorderColor:
      - "#fabd2f"
      - "bold"
    unstagedChangesColor:
      - "#fb4934"
    selectedLineBgColor:
      - "#665c54"
    searchingActiveBorderColor:
      - "bold"
  nerdFontsVersion: "3"
quitOnTopLevelReturn: true
