add_newline = false
command_timeout = 2000

[time]
disabled = false
use_12hr = true
format = "[$time]($style) "

[line_break]
# disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[❌](bold red)"
