add_newline = false
command_timeout = 2000
format = '$time$all'

[directory]
truncation_symbol = "… "
truncation_length = 10
truncate_to_repo = false
use_os_path_sep = false

[time]
disabled = false
use_12hr = true
format = "[$time]($style) "

[deno]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[kotlin]
symbol = " "

[gradle]
symbol = " "
