add_newline = false
command_timeout = 2000
format = '$time$all'

[time]
disabled = false
use_12hr = true
format = "[$time]($style) "

[deno]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[❌](bold red)"
