enable_nightly_info = false
enable_release_build = false
downloads_location = "$HOME/.local/share/bob"
installation_location = "$HOME/.local/share/bob/nvim-bin"
rollback_limit = 3
github_mirror = "https://github.com"
