export module cargo.nu
export module dnf.nu
export module gh.nu
export module git.nu
export module hashicorp.nu
export module state.nu
export module link.nu
export module pacman.nu
export module scoop.nu
export module yay.nu
export module winget.nu
