export use cargo.nu
export use dnf.nu
export use gh.nu
export use git.nu
export use hashicorp.nu
export use state.nu
export use link.nu
export use pacman.nu
export use paru.nu
export use scoop.nu
export use yay.nu
export use winget.nu
